import type { Stage, Tier } from '@/features/pricing';

export interface ProjectPreset {
  id: string;
  label: string;
  tagline: string;
  tier: Tier;
  deliverables: string;
  services: string[];
  team: { roleId: string; stage: Stage }[];
}

/** Pontos de partida por tipo de produção: já marcam serviços, horas e equipe típicas. */
export const PROJECT_PRESETS: ProjectPreset[] = [
  {
    id: 'redes',
    label: 'Conteúdo para redes',
    tagline: 'Reels, TikTok e Shorts',
    tier: 1,
    deliverables: '4 vídeos verticais de até 60 segundos',
    services: [
      'briefing',
      'roteiro',
      'montagem-set',
      'captacao',
      'backup',
      'edicao',
      'legendas',
      'trilha',
      'revisoes',
      'entrega',
    ],
    team: [],
  },
  {
    id: 'institucional',
    label: 'Vídeo institucional',
    tagline: 'Empresa, marca ou serviço',
    tier: 2,
    deliverables: '1 vídeo de 2 a 3 minutos + 2 cortes para redes',
    services: [
      'briefing',
      'roteiro',
      'decupagem-tecnica',
      'visita-tecnica',
      'documentacao',
      'montagem-set',
      'captacao',
      'entrevistas',
      'backup',
      'decupagem-material',
      'edicao',
      'color',
      'motion',
      'audio',
      'trilha',
      'cortes',
      'revisoes',
      'entrega',
    ],
    team: [{ roleId: 'assistente', stage: 'producao' }],
  },
  {
    id: 'evento',
    label: 'Cobertura de evento',
    tagline: 'Congressos, shows e lançamentos',
    tier: 2,
    deliverables: '1 aftermovie de 2 minutos + 3 cortes para redes',
    services: [
      'briefing',
      'decupagem-tecnica',
      'montagem-set',
      'captacao',
      'entrevistas',
      'backup',
      'decupagem-material',
      'edicao',
      'color',
      'trilha',
      'cortes',
      'revisoes',
      'entrega',
    ],
    team: [{ roleId: 'cinegrafista', stage: 'producao' }],
  },
  {
    id: 'casamento',
    label: 'Casamento e social',
    tagline: 'Cerimônia, festa e teaser',
    tier: 2,
    deliverables: '1 filme de 8 a 12 minutos + teaser de 1 minuto',
    services: [
      'briefing',
      'visita-tecnica',
      'montagem-set',
      'captacao',
      'drone',
      'backup',
      'decupagem-material',
      'edicao',
      'color',
      'audio',
      'trilha',
      'revisoes',
      'entrega',
    ],
    team: [{ roleId: 'cinegrafista', stage: 'producao' }],
  },
  {
    id: 'publicidade',
    label: 'Filme publicitário',
    tagline: 'Campanhas e comerciais',
    tier: 3,
    deliverables: '1 filme de 30 segundos + versões de 15 e 6 segundos',
    services: [
      'briefing',
      'roteiro',
      'storyboard',
      'decupagem-tecnica',
      'visita-tecnica',
      'producao-locacao',
      'documentacao',
      'montagem-set',
      'captacao',
      'backup',
      'decupagem-material',
      'edicao',
      'color',
      'motion',
      'audio',
      'trilha',
      'locucao',
      'revisoes',
      'entrega',
    ],
    team: [
      { roleId: 'diretor-fotografia', stage: 'producao' },
      { roleId: 'gaffer', stage: 'producao' },
      { roleId: 'som-direto', stage: 'producao' },
      { roleId: 'produtor', stage: 'pre' },
      { roleId: 'maquiagem', stage: 'producao' },
    ],
  },
  {
    id: 'documentario',
    label: 'Minidocumentário',
    tagline: 'Histórias reais e personagens',
    tier: 3,
    deliverables: '1 documentário de 10 a 15 minutos',
    services: [
      'briefing',
      'roteiro',
      'decupagem-tecnica',
      'visita-tecnica',
      'producao-locacao',
      'documentacao',
      'montagem-set',
      'captacao',
      'entrevistas',
      'drone',
      'backup',
      'decupagem-material',
      'edicao',
      'color',
      'audio',
      'trilha',
      'legendas',
      'revisoes',
      'entrega',
    ],
    team: [
      { roleId: 'som-direto', stage: 'producao' },
      { roleId: 'assistente', stage: 'producao' },
    ],
  },
];

export const TIER_META: Record<Tier, { label: string; description: string }> = {
  1: { label: 'Simples', description: 'Redes sociais, pouca estrutura' },
  2: { label: 'Intermediária', description: 'Institucional, eventos, social' },
  3: { label: 'Complexa', description: 'Publicidade, cinema, documentário' },
};
